### ISSUE TITLE
"nvidia-docker" command is deprecated. 

### ISSUE THREAD

**Issue by yuis-ice** [hukkelas/DeepPrivacy#16]
I tried use it with docker, but I am stuck on the command with nvidia-docker: `nvidia-docker run --rm  -it -v $PWD:/workspace  -e CUDA_VISIBLE_DEVICES=0 deep_privacy python -m deep_privacy.train models/large/config.yml`

After installation of nvidia-docker, I could command like this `docker run --gpus all nvidia/cuda:10.0-base nvidia-smi` but not like `nvidia-docker run `.

I am not familiar with nvidia-docker, I'd really appreciate that if you could tell me how to run your program on docker.

[nvidia-docker: command not found · Issue #1028 · NVIDIA/nvidia-docker](https://github.com/NVIDIA/nvidia-docker/issues/1028)

**Comment by hukkelas** [comment]
If you're not familiar with docker, I recommend you to not use it (if not required by your  system administration etc).

I'm planning to make a easier setup tutorial in the future but in short:

1. Make sure you have Python 3.6 or higher installed.
2. Install Pytorch version 1.0 or higher (we've tested with 1.0, 1.1, 1.2 and 1.3 and it looks OK). To install pytorch, follow the tutorial here: https://pytorch.org/get-started/locally/
3. Install requirements:
```
pip install -r docker/requirements.txt
```
3. Install NVIDIA Apex: https://github.com/nvidia/apex. You can do this with a pytorch only build:
```bash
pip install git+https://github.com/nvidia/apex
```
 
Can you check if this works instead?
