### ISSUE TITLE
Get bounding boxes and keypoints

### ISSUE THREAD

**Issue by IbrahimSobh** [hukkelas/DeepPrivacy#17]
Dear 

Is there a way (API) to get the bounding boxes and key points detected?  (For example, in terms of a list of x,y,w,h for bounding boxes and x,y for each key point)

Best Regards

**Comment by hukkelas** [comment]
No, not really... But you could modify the code to cache it.

We are retrieving bounding boxes and keypoints here:
https://github.com/hukkelas/DeepPrivacy/blob/c1ee9983e8cbedaca6215e3f8fc695b6eb7b8bdc/deep_privacy/inference/anonymizer.py#L39

They are inputted to the function here:
https://github.com/hukkelas/DeepPrivacy/blob/c1ee9983e8cbedaca6215e3f8fc695b6eb7b8bdc/deep_privacy/inference/deep_privacy_anonymizer.py#L30

I guess you could cache it in either places :)

**Comment by IbrahimSobh** [comment]
Thank you very much

Moreover, I guess I can _feed_ my own boxes and key-points (extracted by my own method). For example: 

```
# get my own boxes and points
im_bboxes, im_keypoints = my_function(image)
# call the anonymization as usual  
anonymize_images(self, images, im_keypoints, im_bboxes)

```
Is this correct? 

Regards

**Comment by hukkelas** [comment]
Sorry for the late reply. Yes, this seems correct!
