### ISSUE TITLE
bad result on big faces

### ISSUE THREAD

**Issue by sajjadaemmi** [hukkelas/DeepPrivacy#20]
As I understand, this algorithm works well on small faces in the image. But for large faces (larger than 128 x 128), the output is not suitable. 
Is there a solution?
Is this a problem because the output of the generator network is 128 x 128?

**Comment by hukkelas** [comment]
Yep, the output of the generator is 128x128.
There should be no problem scaling it up to 256x256, but the dataset we train on (FDF) has a max resolution is currently 128x128.

**Comment by sajjadaemmi** [comment]
thank you.
How can I generate output with 256 size?

**Comment by hukkelas** [comment]
Currently this is not supported. You would have to train a generator for 256x256, but we don't have the dataset for this currently.

**Comment by jamestalmage** [comment]
@hukkelas Why not train on [this dataset](https://github.com/NVlabs/ffhq-dataset)? Is 70,000 images not enough? Or is it a compute power issue?

**Comment by hukkelas** [comment]
We did some early experiments on the CelebA-HQ dataset, which is quite similar to the FFHQ dataset. This gave quite poor results for real world use cases, as the CelebA dataset is **very biased** and the model would output a face looking like a "celebrity" and it did not handle different poses of the same face.

We have not experimented with the FFHQ dataset as of yet. However, if one should train a model on the FFHQ dataset, one should use the unaligned (not cropped) images to make it work for inference with a variety of poses.
As I see it, FFHQ does have the original images; however, they are not annotated with landmarks/bounding boxes.
