### ISSUE TITLE
Use on CCTV videos + stitch_face method

### ISSUE THREAD

**Issue by daiisuke27** [hukkelas/DeepPrivacy#23]
Hello, thanks for the great work !
I'am currently new to this, but im trying to use your code to anonymize face on cctv footage, do you think i should use it as it is or i should re-train your model on a cctv dataset ( using your pre-trained weights obviously ) ?
I have two other questions : 
- what does those parameters mean : `use_static_z` , `max_face_size` ?
- if i want to keep the generated face of a person in the next frame (i.e. face swapping the generated face to the original face in the next frame) because that person's face didnt move much, can i do that with `stitch_face` method ? (if you can explain what `stitch_face` and `replace_face` methods exactly do i will be very grateful).

Thank you so much !

**Comment by hukkelas** [comment]
> I'm currently new to this, but im trying to use your code to anonymize face on cctv footage, do you think i should use it as it is or i should re-train your model on a cctv dataset ( using your pre-trained weights obviously ) ?

Try the pretrained network first and check how well it works.If you don't get satisfactory results, I would finetune it on your dataset.


> what does those parameters mean : use_static_z , max_face_size?

use_static_z is a toggle to turn on/off to generate diverse results per face. If not, it will generate the same face each time
max_face_size is a threshold to filter out very large faces, this is usually not used. But for example, if you want to only anonymizse people in the background of a video (not people standing right infront of the camera) you could use this threshold.
