### ISSUE TITLE
Issue building the Docker container

### ISSUE THREAD

**Issue by ticlazau** [hukkelas/DeepPrivacy#26]
Hello, 

I am trying to build the docker container using proposed docker file, but I am getting this error:
-- cut here --
  Found link https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl#sha256=51f1c7514530bd5c145d8f13ed936ad6b8bfcb8cf74e10403d0890bc986f0033 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.4
  Found link https://files.pythonhosted.org/packages/0b/f5/be8e741434a4bf4ce5dbc235aa28ed0666178ea8986ddc10d035023744e6/pip-20.2.4.tar.gz#sha256=85c99a857ea0fb0aedf23833d9be5c40cf253fe24443f0829c7b472e23c364a1 (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*), version: 20.2.4
The command '/bin/sh -c pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./' returned a non-zero code: 1
-- cut here --

This is related to this line in the Dockerfile:
RUN pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

Any advise?
FM

**Comment by hukkelas** [comment]
Hi, Does this issue persist with the new version? 
Note that AMP installation is not longer required if you're not going to train.

Also, the installation process is quite easier, with a setup.py file.

**Comment by ticlazau** [comment]
Hi @hukkelas 

I am getting container build fail just in the beginning because it requires a file requirements.txt to be copied in the container. 
`COPY requirements.txt /workplace`
I belie was not included on the git.

Rgds,
FM

**Comment by hukkelas** [comment]
Sorry for this and the late answer!

Here it is added: https://github.com/hukkelas/DeepPrivacy/blob/master/docker/requirements.txt
