### ISSUE TITLE
Brighter.ai

### ISSUE THREAD

**Issue by pool1892** [hukkelas/DeepPrivacy#3]
Hey, thank you for your research and publishing your source code.

Are you aware of brighter.ai, a Berlin based startup - they are doing more or less what your paper does, but as a product. Maybe you should get in contact and/or mention them in the paper?

Best,
Christoph

**Comment by hukkelas** [comment]
Hey, thank you for notifying me about brighter.ai! I was not aware of their work before now, will definitely take a look at their work!

Thanks,
Håkon
