### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by steenstra** [hukkelas/DeepPrivacy#30]
When running the webcam module, it crashes after some time with a division by zero error. 

`python webcam.py
None
2020-11-23 16:53:20,565 [INFO ]  Loaded model:fdf_512
2020-11-23 16:53:23,362 [INFO ]  Generator initialized with 47.39M parameters
{'type': 'RCNNDetector', 'keypoint_threshold': 0.2, 'densepose_threshold': 0.3, 'simple_expand': False, 'align_faces': False, 'resize_background': True, 'face_detector_cfg': {'name': 'RetinaNetResNet50', 'confidence_threshold': 0.1, 'nms_iou_threshold': 0.3, 'max_resolution': 1080, 'fp16_inference': True, 'clip_boxes': True}, 'rcnn_batch_size': 8}
Traceback (most recent call last):
  File "webcam.py", line 48, in <module>
    print("FPS:", frames / (time.time() - t), end="\r")
ZeroDivisionError: float division by zero
`

The same happens with a different model:
`python webcam.py -m fdf128_retinanet128
None
2020-11-23 16:52:23,881 [INFO ]  Loaded model:retinanet128
2020-11-23 16:52:25,888 [INFO ]  Generator initialized with 3.17M parameters
{'type': 'BaseDetector', 'keypoint_threshold': 0.2, 'densepose_threshold': 0.3, 'simple_expand': True, 'align_faces': False, 'resize_background': True, 'face_detector_cfg': {'name': 'RetinaNetResNet50', 'confidence_threshold': 0.1, 'nms_iou_threshold': 0.3, 'max_resolution': 1080, 'fp16_inference': True, 'clip_boxes': True}}
Traceback (most recent call last):
  File "webcam.py", line 48, in <module>
    print("FPS:", frames / (time.time() - t), end="\r")
ZeroDivisionError: float division by zero
`

**Comment by hukkelas** [comment]
This commit should fix the problem. Please update to latest master branch.
https://github.com/hukkelas/DeepPrivacy/commit/f84cee4d7044946e7f24cc336e800a8472df903d

**Comment by steenstra** [comment]
Yes, this has resolved the issue, thanks!
