### ISSUE TITLE
Preserving gender, age, etc

### ISSUE THREAD

**Issue by IbrahimSobh** [hukkelas/DeepPrivacy#32]
Thank you for the great work! 

Regarding the paper, it is mentioned that:

- "By design, our generator **never observes the original face**, ensuring removal of any privacy-sensitive information"
- "Our model is based on a conditional generative adversarial network, generating images considering the original **pose and image background**"

My question is how the model preserves the gender, age and other related features while generating the faces?

Regards

**Comment by hukkelas** [comment]
> My question is how the model preserves the gender, age and other related features while generating the faces?

That's an interesting question! We have not done any study on this, but would definitely be an interesting question to study. Therefore, I'm not able to backup these statements by any empirical studies or large scale qualitative studies, only from my experience (by looking at examples)-

We have not seen any major bias towards any gender and the model usually keeps some features in the anonymized image that are shown on the rest of the body (not only the face). For example, if the model observes glasses on the ear, it usually generates a pair of glasses. If it's possible to observer the original skin color, it usually generates similar skin colors.
However, it is worth mentioning that the [FDF dataset](https://github.com/hukkelas/FDF) is collected from flicker, and therefore, contains any bias that the website has.
