### ISSUE TITLE
Temporal consistency

### ISSUE THREAD

**Issue by IbrahimSobh** [hukkelas/DeepPrivacy#33]
Thank you for this work 

It is mentioned in the paper, temporal consistency can be one of the proposed improvements. 

- Did you implement any kind of temporal consistency method in this code?  (Based on the results shown as the animated gif, I do not think so)
- Do you have any recommendations, guidelines etc? 

Regards

**Comment by hukkelas** [comment]
> Did you implement any kind of temporal consistency method in this code? (Based on the results shown as the animated gif, I do not think so)

Nope, no temporal consistency is considered as of yet.

> Do you have any recommendations, guidelines etc?

I would recommend to read up on the "Video Inpainting" academic field. [This paper](https://openaccess.thecvf.com/content_ICCV_2019/papers/Chang_Free-Form_Video_Inpainting_With_3D_Gated_Convolution_and_Temporal_PatchGAN_ICCV_2019_paper.pdf)  is probably a good starting point.
