### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by yuan0101213** [hukkelas/DeepPrivacy#34]
I am very interested in your work  and have studied it carefully.But there are some questions when I run the program in docker.I wonder if there is a problem with the docker I created.
Traceback (most recent call last):
  File "/workspace/DeepPrivacy/deep_privacy/inference/infer.py", line 44, in load_model_from_checkpoint
    ckpt = get_checkpoint(cfg.output_dir, validation_checkpoint_step)
  File "/workspace/DeepPrivacy/deep_privacy/engine/checkpointer.py", line 48, in get_checkpoint
    return load_checkpoint(path)
  File "/workspace/DeepPrivacy/deep_privacy/engine/checkpointer.py", line 29, in load_checkpoint
    raise FileNotFoundError(f"Did not find path: {ckpt_path}")
FileNotFoundError: Did not find path: outputs/workspace/deep_privacy_cache/fdf_512/checkpoints

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anonymize.py", line 5, in <module>
    cli.main()
  File "/workspace/DeepPrivacy/deep_privacy/cli.py", line 113, in main
    return_cfg=True)
  File "/workspace/DeepPrivacy/deep_privacy/build.py", line 66, in build_anonymizer
    generator = load_model_from_checkpoint(cfg)
  File "/workspace/DeepPrivacy/deep_privacy/inference/infer.py", line 47, in load_model_from_checkpoint
    ckpt = load_checkpoint_from_url(cfg.model_url)
  File "/workspace/DeepPrivacy/deep_privacy/engine/checkpointer.py", line 18, in load_checkpoint_from_url
    model_url, map_location=_get_map_location())
  File "/opt/conda/lib/python3.6/site-packages/torch/hub.py", line 494, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile

**Comment by hukkelas** [comment]
I believe this was an error with pytorch, could you try to replace the base docker image such that the first line in the docker image is the following:

```
FROM nvcr.io/nvidia/pytorch:20.12-py3
```

**Comment by pddp** [comment]
Hello World,
I tried the git version and failed to get it running - details will follow. I also failed with the docker image:
  Created wheel for wrapt: filename=wrapt-1.12.1-cp36-cp36m-linux_x86_64.whl size=69696 sha256=bc8b02eb0456bbc2988e59f5ded83f5dea050fa6b382093be8af7e8809f3d18e                                                                                                                                                                
  Stored in directory: /root/.cache/pip/wheels/32/42/7f/23cae9ff6ef66798d00dc5d659088e57dbba01566f6c60db63                                                                                                                                                                                                                     
Successfully built gast wrapt                                                                                                                                                                                                                                                                                                  
Installing collected packages: google-pasta, tensorboard, keras-applications, keras-preprocessing, gast, tensorflow-estimator, astor, wrapt, opt-einsum, tensorflow                                                                                                                                                            
ERROR: thinc 6.12.1 has requirement msgpack<0.6.0,>=0.5.6, but you'll have msgpack 0.6.1 which is incompatible.
ERROR: thinc 6.12.1 has requirement wrapt<1.11.0,>=1.10.0, but you'll have wrapt 1.12.1 which is incompatible.
  Attempting uninstall: tensorboard                                                                                                                                                                                                                                                                                            
    Found existing installation: tensorboard 2.1.0                                                                                                                                                                                                                                                                             
    Uninstalling tensorboard-2.1.0:                                                                                                                                                                                                                                                                                            
      Successfully uninstalled tensorboard-2.1.0                                                                                                                                                                                                                                                                               
  Attempting uninstall: wrapt                                                                                                                                                                                                                                                                                                  
    Found existing installation: wrapt 1.10.11
ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.                                                                                                                                            
The command '/bin/sh -c pip install tensorflow==1.15' returned a non-zero code: 1 

I assume that the docker image does not specify the required version numbers for some of the packages.

**Comment by hukkelas** [comment]
You can remove the install of Tensorflow in the last line, as this is only required for computing FID values.

That is, remove this line:
https://github.com/hukkelas/DeepPrivacy/blob/de30f547428277385db6b0536c9b74750f56e1eb/docker/Dockerfile#L24

**Comment by raphaelmemmesheimer** [comment]
> You can remove the install of Tensorflow in the last line, as this is only required for computing FID values.
> 
> That is, remove this line:
> 
> https://github.com/hukkelas/DeepPrivacy/blob/de30f547428277385db6b0536c9b74750f56e1eb/docker/Dockerfile#L24

Thanks, that in combination with using the most recent `torchvision` version worked for me.
