### ISSUE TITLE
output image resolution

### ISSUE THREAD

**Issue by jim-bo** [hukkelas/DeepPrivacy#38]
Hello,
I was wondering how the resolution of the output images is chosen? Is this a parameter of the model, which could be trained to output higher resolution images?

Alternatively do you think it is reasonable to cut-out the face from a higher resolution image and input this into your program, then re-integrate into the original resolution image? If so, how much context surrounding the face would be good to include in these subsets?

My goal is to benchmark how this tool works on high resolution images.

Thanks,
James

**Comment by hukkelas** [comment]
Hi, sorry for the late answer!

> I was wondering how the resolution of the output images is chosen? Is this a parameter of the model, which could be trained to output higher resolution images?

This is a parameter chosen before training. Currently it only supports 128x128, but we are looking into training larger models.
