### ISSUE TITLE
Different results on same input

### ISSUE THREAD

**Issue by unknownoperation** [hukkelas/DeepPrivacy#39]
Thanks for the great repository!

I just wonder, could the anonymization network generate different results on the same input image? 
There is no manual seed selection in code, that I could find in your repository.

The only thing that works for me:
```
anonymizer = build_anonymizer(model_name="fdf128_rcnn512", truncation_level=100)
torch.manual_seed(int(time.time()))
np.random.seed(int(time.time()))
res = anonymizer.detect_and_anonymize_images([in_image])
```

**Comment by hukkelas** [comment]
> I just wonder, could the anonymization network generate different results on the same input image?

Yep, that should be possible if you set truncation_level to "None" or a large number as you have

> There is no manual seed selection in code, that I could find in your repository.

There should be no need to set the seed to generate random faces. If you want to always generate the same output, you can set truncation_level to 0.
