### ISSUE TITLE
ImportError: cannot import name 'compare_ssim' from 'skimage.measure'

### ISSUE THREAD

**Issue by teo9822** [hukkelas/DeepPrivacy#41]
When you start anonymize.py you get an ImportError

**Comment by ravi97** [comment]
I had the same issue. Apparently the latest version of scikit-image does not have the function skimage.measure.compare_ssim. Try downgrading your scikit-image version to 0.16.

**Comment by andmagdo** [comment]
As documented in the notes [here](https://scikit-image.org/docs/dev/api/skimage.metrics.html?highlight=compare_ssim), "This function was renamed from skimage.measure.compare_ssim to skimage.metrics.structural_similarity" and for compare_psnr, "This function was renamed from skimage.measure.compare_psnr to skimage.metrics.peak_signal_noise_ratio." I will soon make a fork that replaces these with the new versions.
