### ISSUE TITLE
The result of the face swap is scary

### ISSUE THREAD

**Issue by bberzh** [hukkelas/DeepPrivacy#48]
Hi, I apply your creative code on my own data, but find some results of the face swap are scary. I think going back to targeted training might help. Could you  teach me how to train with my own data？ thank you so much!

**Comment by hukkelas** [comment]
Please take a look at previous issues:
https://github.com/hukkelas/DeepPrivacy/issues/29
https://github.com/hukkelas/DeepPrivacy/issues/36
