### ISSUE TITLE
Anonymization on Windows 

### ISSUE THREAD

**Issue by Ternowy** [hukkelas/DeepPrivacy#5]
I tried to install that on Windows, all packages were successful downloaded.

Now i'm trying to run command

`python -m deep_privacy.inference.anonymize_folder model/default/config.yml --source_path testim.jpg --target_path testim_anonymized.jpg`

I changed after failure **model** to **models** 

`python -m deep_privacy.inference.anonymize_folder models/default/config.yml --source_path testim.jpg --target_path testim_anonymized.jpg`

after running this command i get 

`C:\Users\Alexander\Work\NN\DeepPrivacy>python -m deep_privacy.inference.anonymize_folder models/default/config.yml --source_path testim.jpg --target_path testim_anonymized.jpg
CONFIG USED:
logging.num_ims_per_log                            500
logging.num_ims_per_save_image                     100000
logging.num_ims_per_checkpoint                     200000
max_imsize                                         128
use_full_validation                                False
load_fraction_of_dataset                           False
dataset                                            yfcc100m128
train_config.transition_iters                      1200000
train_config.learning_rate                         0.00175
train_config.amp_opt_level                         O1
train_config.batch_size_schedule                   {4: 256, 8: 256, 16: 256, 32: 128, 64: 96, 128: 64}
train_config.criterion.type                        wgan
train_config.criterion.gradient_penalty_weight     10
train_config.criterion.epsilon_penalty_weight      0.001
train_config.criterion.different_images            False
models.start_channel_size                          256
models.pose_size                                   14
models.image_channels                              3
models.generator.running_average_decay             0.999
models.discriminator.structure                     normal
config_path                                        models/default/config.yml
checkpoint_dir                                     models/default\checkpoints
generated_data_dir                                 models/default\generated_data
summaries_dir                                      models/default\summaries
source_path                                        testim.jpg
target_path                                        testim_anonymized.jpg

Traceback (most recent call last):
  File "C:\Users\Alexander\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Alexander\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alexander\Work\NN\DeepPrivacy\deep_privacy\inference\anonymize_folder.py", line 5, in <module>
    generator, imsize, source_path, image_paths, save_path = infer.read_args()
  File "C:\Users\Alexander\Work\NN\DeepPrivacy\deep_privacy\inference\infer.py", line 176, in read_args
    ckpt = utils.load_checkpoint(config.checkpoint_dir)
  File "C:\Users\Alexander\Work\NN\DeepPrivacy\deep_privacy\utils.py", line 43, in load_checkpoint
    with open(os.path.join(ckpt_dir_or_file, 'latest_checkpoint')) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/default\\checkpoints\\latest_checkpoint'`

How can i fix it?

**Comment by hukkelas** [comment]
Hi. Making this work on windows might be a hassle, since all development and testing is done in Ubuntu 16.04/18.04. 

If you only want to test our model on different images, I recommend running our system in [Google Colab](https://drive.google.com/open?id=1mR5DcND9JCxqr1rXsavVYKzFQq4gOI5-).

Anyways, I believe the error you are getting is due to how you are giving the path to the model config. Can you try replacing "/" with "\"? (IIRC, this is the standard in windows): 

Like this:
```bash
python -m deep_privacy.inference.anonymize_folder models\default\config.yml --source_path testim.jpg --target_path testim_anonymized.jpg
```

**Comment by Ternowy** [comment]
> Hi. Making this work on windows might be a hassle, since all development and testing is done in Ubuntu 16.04/18.04.
> 
> If you only want to test our model on different images, I recommend running our system in [Google Colab](https://drive.google.com/open?id=1mR5DcND9JCxqr1rXsavVYKzFQq4gOI5-).
> 
> Anyways, I believe the error you are getting is due to how you are giving the path to the model config. Can you try replacing "/" with ""? (IIRC, this is the standard in windows):
> 
> Like this:
> 
> ```shell
> python -m deep_privacy.inference.anonymize_folder models\default\config.yml --source_path testim.jpg --target_path testim_anonymized.jpg
> ```

Thank You, i'm going to install virtual machine with Ubuntu. 
Yep, that's not best idea to use Windows for it.
I want not only test it, but try full version on my own pc, i think the idea is great and it's definitely useful for different areas like witness protection program or other

**Comment by hukkelas** [comment]
Ok, great. If you have any problems with installing it, don't hesitate to ask! Good luck :)

**Comment by ankur8931** [comment]
Hi @hukkelas . I am getting the checkpoint error similar to the one reported above. 
python3 -m deep_privacy.inference.anonymize_folder DeepPrivacy/models/default/config.yml --source_path DeepPrivacy/devilsec.jpg --target_path testim_anonymized.jpg

_FileNotFoundError: [Errno 2] No such file or directory: 'DeepPrivacy/models/default/checkpoints/latest_checkpoint'_

Does the model assumes presence of checkpoint files? If so can i download them from some google drive where you have saved checkpoint (.ckpt) files?

**Comment by hukkelas** [comment]
Yes. The pretrained models are mentioned in the readme.MD file and can be found here:
https://drive.google.com/open?id=1RXM0xIoaHARrZ87r-PFEVVOc9BjDuWc5

**Comment by daquarti** [comment]
Could you help me?
python3 anonymize.py -s/home/daqua/Pictures/h.png -t/home/daqua/Pictures/h2.png

None
Traceback (most recent call last):
  File "anonymize.py", line 5, in <module>
    cli.main()
  File "/home/daqua/Videos/DeepPrivacy/deep_privacy/cli.py", line 111, in main
    anonymizer, cfg = build_anonymizer(
  File "/home/daqua/Videos/DeepPrivacy/deep_privacy/build.py", line 62, in build_anonymizer
    cfg = get_config(config_urls[model_name])
  File "/home/daqua/Videos/DeepPrivacy/deep_privacy/build.py", line 36, in get_config
    torch.hub.download_url_to_file(config_url, cfg_path)
  File "/home/daqua/.local/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect
