### ISSUE TITLE
Face Detector in Config

### ISSUE THREAD

**Issue by wngTn** [hukkelas/DeepPrivacy#54]
In the README it states that the model fdf128_rcnn512 uses DSFD as face detector. However, the respective config file at: https://folk.ntnu.no/haakohu/configs/fdf_512.json has RetinaNetResNet50 as face detector. Why exactly is that?

**Comment by hukkelas** [comment]
That's an error in the readme. Updated it now!

All current models uses RetinaNet for face detection, but you can freely change the face detector to DSFD without retraining the system.
