### ISSUE TITLE
something wrong with interactive demo

### ISSUE THREAD

**Issue by Ley-lele** [hukkelas/DeepPrivacy#55]
[****](https://huggingface.co/spaces/haakohu/DeepPrivacy)
![image](https://user-images.githubusercontent.com/75935402/227761149-e45dfc9a-a2b4-4ece-8b61-5033176376f7.png)

**Comment by hukkelas** [comment]
Thanks for letting me know! Fixed the error now :)

**Comment by Ley-lele** [comment]
i still get another problems like this. when i input a video, but got output like this. All is blank. 





叶翔乐
***@***.***







                       
Original Email
                       
                     

Sender:"Håkon Hukkelås"< ***@***.*** &gt;;

Sent Time:2023/3/28 14:29

To:"hukkelas/DeepPrivacy"< ***@***.*** &gt;;

Cc recipient:"Ley"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [hukkelas/DeepPrivacy] something wrong with interactive demo(Issue #55)




 
Closed #55 as completed.
 
&mdash;
